apiVersion: v1
kind: Service
metadata:
  name: external-service-mastodon
  namespace: mastodon
spec:
  type: ExternalName
  externalName: "${SECRET_DOMAIN}"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-mastodon
  namespace: mastodon
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: "${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mastodon
            port:
              number: 443
  tls:
  - hosts:
    - "${SECRET_DOMAIN}"
