---
apiVersion: v1
kind: Service
metadata:
  name: mastodon
  namespace: mastodon
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mastodon
  namespace: mastodon
subsets:
- addresses:
  - ip: 137.184.168.240
  ports:
  - name: https
    port: 443
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mastodon
  namespace: mastodon
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mastodon
            port:
              number: 443
