apiVersion: v1
kind: Service
metadata:
  name: external-service-mastodon
  namespace: mastodon
spec:
  type: ExternalName
  externalName: "${SECRET_DOMAIN}" # eg example.example.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-mastodon
  namespace: mastodon
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" #important
spec:
  rules:
  - host: "${SECRET_DOMAIN}" # eg external-service.yourdomain.com
    http:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mastodon
            port:
              number: 443 # eg 4589
  tls:
  - hosts:
    - "${SECRET_DOMAIN}"
