---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-fediverse-lemmy-lemmy
  namespace: flux-system
spec:
  prune: true
  sourceRef:
    kind: helmchart
    name: lemmy
  interval: 30m
  retryInterval: 1m
  timeout: 5m
