---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: admin-user
      remoteRef:
        key: GRAFANA_ADMIN_USER
    - secretKey: admin-password
      remoteRef:
        key: GRAFANA_ADMIN_PASSWORD
