---
# Area
- name: area/ansible
  color: "0e8a16"
- name: area/github
  color: "0e8a16"
- name: area/kubernetes
  color: "0e8a16"
- name: area/template
  color: "0e8a16"
# Renovate
- name: renovate/ansible
  color: "027fa0"
- name: renovate/container
  color: "027fa0"
- name: renovate/github-action
  color: "027fa0"
- name: renovate/github-release
  color: "027fa0"
- name: renovate/helm
  color: "027fa0"
# Semantic Type
- name: type/patch
  color: "ffec19"
- name: type/minor
  color: "ff9800"
- name: type/major
  color: "f6412d"
- name: type/break
  color: "f6412d"
# Uncategorized
- name: bug
  color: "ee0701"
- name: do-not-merge
  color: "ee0701"
- name: docs
  color: "F4D1B7"
- name: enhancement
  color: "84b6eb"
- name: broken-links
  color: "7B55D7"
- name: question
  color: "cc317c"
- name: community
  color: "0e8a16"
