apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: "2023-06-12T12:00:32Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  labels:
    kustomize.toolkit.fluxcd.io/name: cluster-fediverse-lemmy
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: lemmy
  namespace: lemmy
  resourceVersion: "762575"
  uid: a44baacb-61d3-4689-9c70-9cc7d764ae6f
spec:
  chart:
    spec:
      chart: ./charts/lemmy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: lemmy
        namespace: flux-system
      version: 0.1.0
  install:
    createNamespace: true
    remediation:
      strategy: uninstall
      retries: 10
      remediatelastFailure: true
    timeout: 10m
  interval: 15m
  maxHistory: 2
  uninstall:
    keepHistory: false
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  values:
    admin:
      email: jax-admin@cloudhub.social
      username: jax-admin
    backend:
      affinity: {}
      env:
        RUST_BACKTRACE: full
        RUST_LOG: warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info
      envFrom: null
      image:
        _keep: true
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext:
        fsGroup: 1004
      replicaCount: 1
      securityContext:
        runAsUser: 1004
      service:
        port: 80
        type: ClusterIP
      tolerations: []
    config:
      tls: true
    frontend:
      affinity: {}
      env:
        LEMMY_UI_DEBUG: false
        RUST_BACKTRACE: "1"
      envFrom: null
      image:
        repository: dessalines/lemmy-ui
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext:
        fsGroup: 1004
      replicaCount: 1
      securityContext:
        runAsUser: 1004
      service:
        port: 80
        type: ClusterIP
      tolerations: []
    fullnameOverride: ""
    image:
      pullPolicy: IfNotPresent
      repository: dessalines/lemmy
    imagePullSecrets: []
    ingress:
      annotations:
        external-dns.alpha.kubernetes.io/target: ingress.cloudhub.social
        hajimari.io/icon: simple-icons:lemmy
      className: nginx
      enabled: true
      hosts:
      - lemmy.cloudhub.social
      tls:
      - hosts:
        - lemmy.cloudhub.social
        secretName: letsencrypt-production
    nameOverride: ""
    pictrs:
      affinity: {}
      env:
        PICTRS__MEDIA__GIF__MAX_AREA: 65536
        PICTRS__MEDIA__GIF__MAX_FRAME_COUNT: 400
        PICTRS__MEDIA__GIF__MAX_HEIGHT: 256
        PICTRS__MEDIA__GIF__MAX_WIDTH: 256
        PICTRS__MEDIA__VIDEO_CODEC: vp9
      envFrom: null
      image:
        pullPolicy: IfNotPresent
        repository: asonix/pictrs
        tag: 0.4.0-beta.19
      nodeSelector: {}
      persistence:
        accessMode: ReadWriteOnce
        enabled: true
        existingClaim: lemmy-data-pictrs-storage-0
        size: 16Gi
        storageClass: nfs-client
      podAnnotations: {}
      podSecurityContext:
        fsGroup: 1004
      replicaCount: 1
      securityContext:
        runAsUser: 1004
      service:
        port: 80
        type: ClusterIP
      storage:
        method: filesystem
        objectStorage:
          usePathStyle: false
      tolerations: []
    postgresql:
      auth:
        database: lemmy
        username: lemmy
      enabled: true
      image:
        debug: true
      metrics:
        enabled: true
        prometheusRule:
          enabled: true
        serviceMonitor:
          enabled: true
      primary:
        containerSecurityContext:
          runAsUser: 1004
        persistence:
          enabled: true
          existingClaim: lemmy-data-postgres-storage-0
          storageClass: nfs-client
        volumePermissions:
          enabled: true
      service:
        port: 5432
    proxy:
      affinity: {}
      enabled: true
      image:
        pullPolicy: Always
        repository: nginx
        tag: 1-alpine
      nodeSelector: {}
      podAnnotations: {}
      podSecurityContext: {}
      replicaCount: 1
      securityContext: {}
      service:
        port: 80
        type: ClusterIP
      tolerations: []
    serverName: lemmy.cloudhub.social
    serviceAccount:
      annotations: {}
      create: true
      name: ""
    smtp:
      from: lemmy-noreply@cloudhub.social
      server: smtp.sendgrid.net
      tls: starttls
      username: apikey
  valuesFrom:
  - kind: Secret
    name: lemmy-secret
    targetPath: smtp.smtp_password
    valuesKey: smtp_password
  - kind: Secret
    name: lemmy-secret
    targetPath: admin.password
    valuesKey: admin_password
  - kind: Secret
    name: lemmy-secret
    targetPath: pictrs.apiKey
    valuesKey: pictrs_api_key
  - kind: Secret
    name: lemmy-secret
    targetPath: postgresql.auth.password
    valuesKey: postgresql_password
  - kind: Secret
    name: lemmy-secret
    targetPath: config.siteName
    valuesKey: site_name
status:
  conditions:
  - lastTransitionTime: "2023-06-12T12:01:16Z"
    message: Release reconciliation succeeded
    reason: ReconciliationSucceeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-06-12T12:01:16Z"
    message: Helm install succeeded
    reason: InstallSucceeded
    status: "True"
    type: Released
  helmChart: flux-system/lemmy-lemmy
  lastAppliedRevision: 0.1.0
  lastAttemptedRevision: 0.1.0
  lastAttemptedValuesChecksum: ad747212e638bd4cf51112fae75cd8918299ee90
  lastReleaseRevision: 1
  observedGeneration: 1
