---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: crunchy-postgres-operator
  namespace: flux-system
spec:
  interval: 10m
  url: oci://registry.developers.crunchydata.com/crunchydata/pgo
  ref:
    tag: 5.5.2
