---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: 4.0.22
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  values:
    envVars:
      - name: WEAVE_GITOPS_FEATURE_OIDC_BUTTON_LABEL
        value: "Login with Authentik"
      # - name: WEAVE_GITOPS_AUTH_ENABLED
      #   value: "true"
    adminUser:
      create: true
      username: admin
    ingress:
      enabled: true
      className: nginx
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
        hajimari.io/icon: simple-icons:sawtooth-wave
        hajimari.io/enable: "true"
      hosts:
        - host: &host "gitops.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    networkPolicy:
      create: false
    metrics:
      enabled: true
    rbac:
      create: true
      # impersonationResourceNames: ["admin", "wego-admin", "wego-readonly"]
      # impersonationResourceNames: ["admin", "aaawego-admin", "aaawego-readonly"]
      # impersonationResources: ["users", "groups"]
    podAnnotations:
      secret.reloader.stakater.com/reload: weave-gitops-secret
  valuesFrom:
    - kind: Secret
      name: weave-gitops-secret
      valuesKey: adminPassword
      targetPath: adminUser.passwordHash

