apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: lemmy
  namespace: lemmy
spec:
  dataVolumeClaimSpec:
    storageClassName: nfs-client
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: 1Gi
  serverGroups: # 2
    - name: lemmy-postgres
      postgresClusterSelector: {}
