apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: pgadmin
  namespace: postgres
spec:
  dataVolumeClaimSpec:
    storageClassName: nfs-client
    accessModes:
      - "ReadWriteOnce"
    resources:
      requests:
        storage: 1Gi
  serverGroups: # 2
    - name: lemmy-postgres
      postgresClusterSelector: {}
  config:
    settings:
      AUTHENTICATION_SOURCES: ["oauth2", "internal"]
      OAUTH2_CONFIG:
        - OAUTH2_NAME: "authentik"
          OAUTH2_DISPLAY_NAME: "Authentik"
          OAUTH2_CLIENT_ID: "${PGADMIN_PGO_OIDC_CLIENT_ID}"
          OAUTH2_CLIENT_SECRET: "${PGADMIN_POG_OIDC_CLIENT_SECRET}"
          OAUTH2_TOKEN_URL: "https://auth.${SECRET_DOMAIN}/application/o/token/"
          OAUTH2_AUTHORIZATION_URL: "https://auth.${SECRET_DOMAIN}/application/o/authorize/"
          OAUTH2_API_BASE_URL: "https://auth.${SECRET_DOMAIN}/application/o/"
          OAUTH2_SERVER_METADATA_URL: "https://auth.${SECRET_DOMAIN}/application/o/pgadmin/.well-known/openid-configuration"
          OAUTH2_SCOPE: "openid email profile"
          OAUTH2_USERINFO_ENDPOINT: "userinfo"
          OAUTH2_SSL_CERT_VERIFICATION: "False" # for testing purposes
          OAUTH2_BUTTON_COLOR: "red"
      OAUTH2_AUTO_CREATE_USER: "True"
      DEBUG: true
