machine:
  network:
    kubespan:
      enabled: true
  kubelet:
    extraArgs:
      rotate-server-certificates: true
      # # https://github.com/siderolabs/talos/issues/7216
      # feature-gates:
      #   "NewVolumeManagerReconstruction=false"
    extraMounts:
      - destination: /var/local-path/storage
        type: bind
        source: /var/local-path/storage
        options:
          - bind
          - rshared
          - rw
  install:
    image: "factory.talos.dev/installer/87edef3e4227c6046c17a4d7c7d25e56907bfaf57195d2ccdd66a9f1a934c378:v1.9.4"
    extraKernelArgs:
      - talos.logging.kernel=udp://10.0.41.61:6050/
    systemExtensions:
      officialExtensions:
        - siderolabs/iscsi-tools
        - siderolabs/qemu-guest-agent
  logging:
    destinations:
      - endpoint: "udp://10.0.41.61:6051/"
        format: "json_lines"
cluster:
  discovery:
    enabled: true
