machine:
  network:
    kubespan:
      enabled: true
  kubelet:
    extraArgs:
      rotate-server-certificates: true
      # # https://github.com/siderolabs/talos/issues/7216
      # feature-gates:
      #   "NewVolumeManagerReconstruction=false"
    extraMounts:
      - destination: /var/local-path/storage
        type: bind
        source: /var/local-path/storage
        options:
          - bind
          - rshared
          - rw
  install:
    image: "factory.talos.dev/installer/c482e5a56fb6065057102b9a801aa6e069ffc62528fd98a7c629bd081b768775:v1.9.4"
    extraKernelArgs:
      - talos.logging.kernel=udp://10.0.41.61:6050/
  logging:
    destinations:
      - endpoint: "udp://10.0.41.61:6051/"
        format: "json_lines"
cluster:
  discovery:
    enabled: true
