apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:2VICNZikAF0oYRj91/mH/BPU6pCd5pzI5E2TK9D4EyK7BRVK,iv:TQdch79dIu4r6egFDIHGwYAs79CI6cJyHCCR9hyfTDs=,tag:sIlYcy9aNKClrlsJkDOlWQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:Q/mtroJrS+Js+L/hKVSd1E26TxaFQMidJHeBBZrstezaD+B0ftXqFm+tp5FE9f1Xl2/CEwoSFMGU/+7Dan0p6UhmRvoBbYSIkx04TfgQo9lwV2gIbhIsjdcDcbp2DI/XBfYDfBiBhsL44ske9py5YVi8Su9LFUosvTjRkahHPyapZLOu+kJuZ4kYWqqL2WKXgis5eUIqdxDtoSonttTG303dehDm7/TV11IjDxekQQ==,iv:rtyGZ1kfynwJrW9Ue0aHT+UKo3oa6HDkijfpkAxbIQE=,tag:P5UL8sgL8yYC1xrORecVVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ztgva2tc0wsdchee6a8kenhjtcgwzwy8uhlal60zd6wuxuwgvpzslkhnlg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WU1XeUlmZ1lQYjNlT2lS
            ektRY0xoSFBhRlFzUEVYMTROdmdVaUVwR25JCnZPbHUramdOR0EyaTZVYUxMR05C
            MTI5WTNGcTZlRFJ6aDNHaWhPZVlTS0UKLS0tIFBiRXJxdzM5WllQLzNYWThCZktV
            QXkrS0hsVHRyQ3E4T1FzeHdRNERzb3MKLEuctOXnkrL/efUMfJL9b7L7AI4tL/US
            VnuL7VWALWaeKELwTzqGPkPkQ9keSsIhDsyF5ru9tdNExNO92tC2TA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-06T20:40:07Z"
    mac: ENC[AES256_GCM,data:D1Sg/ELSFQBkCGeDEByMPtEDoTHTU7WYr6MrbkyWJTWAFeH1Zsd3WpNwLJk80ZM9n/A+rR5vTBzDRTX01h0OJKmzIA+fULXDaUfc8utZsXNFxro+wBo9q5IWVB7yT5SK3Cr3Xf0t6rxCYFEb3HMrqWKL4PfXnvWFXfY45aWu//8=,iv:T7rx0XxmkrVwcrsHMfU4DGAeqSDfF//7YbwNj6EYF/Q=,tag:RqKid/DU1AymUcl/aKo3oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
