---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  namespace: networking
  annotations:
    external-dns.alpha.kubernetes.io/target: "status.${SECRET_DOMAIN}"
spec:
  endpoints:
    - dnsName: "status.${SECRET_DOMAIN}"
      recordType: CNAME
      targets: ["stats.uptimerobot.com"]
