---
apiVersion: v1
kind: Service
metadata:
  name: external-service-status
  namespace: networking
spec:
  type: ExternalName
  externalName: stats.uptimerobot.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-status-ingress
  namespace: networking
  annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/upstream-vhost: "stats.uptimerobot.com"
    nginx.ingress.kubernetes.io/server-snippets: |
        set $monitorId k8480TY6yL;
        # server_name status.${SECRET_DOMAIN};
        location / {
                proxy_set_header Host "stats.uptimerobot.com";
                proxy_set_header Accept-Encoding "";
                proxy_pass_request_headers      on;
                proxy_pass https://stats.uptimerobot.com/;
                proxy_ssl_server_name on;

                rewrite ^\/([0-9]+) /$monitorId/$1 break;
                rewrite ^\/$ /$monitorId break;

                sub_filter_once off;
                sub_filter_types text/html;
                sub_filter </head>
                        '</head><style>#main-footer{display:none;}</style>';
                sub_filter "stats.uptimerobot.com" "$host";
                sub_filter "https://stats.uptimerobot.com/$monitorId" "https://$host";
        }
spec:
  rules:
  - host: "status.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service-status
            port:
              number: 443
  tls:
  - hosts:
    - "status.${SECRET_DOMAIN}"
