---
apiVersion: v1
kind: Service
metadata:
  name: external-service-status
  namespace: networking
spec:
  type: ExternalName
  externalName: stats.uptimerobot.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-status-ingress
  namespace: networking
  annotations:
    nginx.ingress.kubernetes.io/server-snippets: |
        location / {
            #proxy requests đến Uptimerobot
            proxy_pass https://stats.uptimerobot.com/k8480TY6yL/;
            #Gửi server_name khi handshake SSL, nếu off thì sẽ bị lỗi SSL
            proxy_ssl_server_name on;
            #Set header này thì response trả về từ Uptimerobot không bị nén, từ đó mình có thể replace ở bước dưới
            proxy_set_header Accept-Encoding "";
            #Uptimerobot dùng header này với giá trị 'upgrade-insecure-requests' để trình duyệt luôn load các css/js với HTTPS. Ẩn header này để có thể truy cập vào status.nddcoder.com mà không cần HTTPS
            proxy_hide_header Content-Security-Policy;
            #Replace 1 số link trong response để website load tài nguyên, các nút trên giao diện hoạt động chính xác
            sub_filter https://stats.uptimerobot.com/k8480TY6yL /;
            sub_filter https://stats.uptimerobot.com/ /;
            #Xóa GTM để Uptimerobot không tracking được mình 😀
            # sub_filter '<script async src="https://www.googletagmanager.com/gtag/js?id=UA-1748433-46"></script>' '';
            # sub_filter </head>
            #         '</head><style>#main-footer{display:none;}</style>';
            #Replace all
            sub_filter_once off;
        }

        #Proxy assets requests
        location /assets {
            proxy_pass https://stats.uptimerobot.com/assets;
            proxy_ssl_server_name on;
        }

        #Proxy api requests
        location /api {
            proxy_pass https://stats.uptimerobot.com/api;
            proxy_ssl_server_name on;
        }
spec:
  rules:
  - host: "status.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service-status
            port:
              number: 443
  tls:
  - hosts:
    - "status.${SECRET_DOMAIN}"
