---
apiVersion: v1
kind: Service
metadata:
  name: external-service-status
  namespace: networking
  # annotations:
  #   coredns.io/hostname: "status.${SECRET_DOMAIN}"
spec:
  type: ExternalName
  externalName: stats.uptimerobot.com
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-status-ingress
  namespace: networking
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "stats.uptimerobot.com"
    nginx.ingress.kubernetes.io/server-snippet: |
        proxy_ssl_name status.${SECRET_DOMAIN};
        proxy_ssl_server_name on;
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # more_clear_input_headers "Host" "X-Forwarded-Host";
      more_set_input_headers 'Host: stats.uptimerobot.com';
      proxy_set_header Host stats.uptimerobot.com;
    # external-dns.alpha.kubernetes.io/target: "status.${SECRET_DOMAIN}"
    # external-dns.alpha.kubernetes.io/hostname: ""
spec:
  rules:
  - host: "status.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service-status
            port:
              number: 443
  tls:
  - hosts:
    - "status.${SECRET_DOMAIN}"
