---
apiVersion: v1
kind: Service
metadata:
  name: external-service-status
  namespace: networking
spec:
  ports:
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-service-status
  labels:
    kubernetes.io/service-name: external-service-status
addressType: IPv4
ports:
  - name: ''
    appProtocol: http
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - "stats.uptimerobot.com"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service-status
  namespace: networking
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/publishedservice: "true"
    external-dns.alpha.kubernetes.io/target: "status.${SECRET_DOMAIN}"
    external-dns.alpha.kubernetes.io/hostname: "stats.uptimerobot.com"
    hajimari.io/icon: simple-icons:list-status
spec:
  rules:
  - host: "status.${SECRET_DOMAIN}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-service-status
            port:
              number: 443
  tls:
  - hosts:
    - "status.${SECRET_DOMAIN}"
