creation_rules:
  - path_regex: .*values.yaml$
    age: age1ztgva2tc0wsdchee6a8kenhjtcgwzwy8uhlal60zd6wuxuwgvpzslkhnlg
  - path_regex: ".*\\.yaml"
    encrypted_regex: ^(data|stringData)$
    age: age1ztgva2tc0wsdchee6a8kenhjtcgwzwy8uhlal60zd6wuxuwgvpzslkhnlg
