---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: promtail
      version: 6.15.3
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  # dependsOn:
  #   - name: rook-ceph-cluster
  #     namespace: rook-ceph
  values:
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
