apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:mxerOoCTfDES7BYtSsfRjVfyREz9+Q==,iv:4kmsfvzDkfCK2yX2Wt2RagSbd/ziKiHe/YK3mVLX/yA=,tag:1ehpUsknotNI3g6axWrvOw==,type:str]
    api-key: ENC[AES256_GCM,data:lsfhSgeDvAT1WtKMAPiGqx/zKHidFZ5+kM/1yeYObBnGdvfx7w==,iv:d1WJmyg1Kb6/zf7vTf7B3zgCfgvB7R6nzgbslJTS2lw=,tag:c/4PYI4rWHaDVEHhVMCIZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ztgva2tc0wsdchee6a8kenhjtcgwzwy8uhlal60zd6wuxuwgvpzslkhnlg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aVNDTldzOGVOOENFYWdG
            MlBvM251TC9nVjdXK3F3MnBFYTBSUm1LTVJjCngybXo5S2RaS1FvK0d4VG14VndH
            VjhhOFBzNW9oSXVHWlJzYXlXN1VoRXcKLS0tIEVaNFpxVldNZWtSSUpIdEhSRy9U
            R2ZweFhhQm41c1NYK0lhbmhOWFZvdWcKxaZ/QM/Mf3PKYhJhBaVLQjMQbhua3UtO
            +8AqRFGxQo3N/Vd1L3+GFLnOM5SqEa5q/hcFL34a2geFb4K+FtJTNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T22:24:56Z"
    mac: ENC[AES256_GCM,data:AqzvLDoxi58m8h+CErnoj3OQLIBhoI6OADZzwuY79UTB74pBehojHy0xbZr39TQ4XNikqsAhIqys3MXn17kxh1bHWoFYBGRl+uIt17BhlmCS4hvy5JcppHuW9lspxpX83AT+XXK1kAvpyqwj1Pu84HTi7IVzQPc8faQlzQbnRlg=,iv:aSFTkrt1msrYFxBZSj0u7fFlKuydwUurp6xiipSilTM=,tag:jN6j9EPYy+M7dl3neKGmvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
