---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
  namespace: nfs-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 10.0.20.50
            - name: NFS_PATH
              value: /mnt/STGNew/CloudHub-NFS
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.0.20.50
            path: /mnt/STGNew/CloudHub-NFS
