---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-authentik
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-external-secrets
  path: ./apps/production/authentik/authentik/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false # no flux ks dependents
  interval: 30m
  retryInterval: 1m
  timeout: 5m
