---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/kubernetes-sigs/nfs-subdir-external-provisioner/deploy
resources:
  - ./namespace.yaml
patchesStrategicMerge:
  - ./nfs-provisioner/patch_nfs_details.yaml
