---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - github.com/kubernetes-sigs/nfs-subdir-external-provisioner/tree/nfs-subdir-external-provisioner-4.0.18/deploy
resources:
  - ./namespace.yaml
patchesStrategicMerge:
  - ./nfs-provisioner/patch_nfs_details.yaml
