---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lemmy
  namespace: lemmy
spec:
  interval: 15m
  chart:
    spec:
      chart: ./charts/lemmy
      version: 0.5.7
      sourceRef:
        kind: GitRepository
        name: lemmy
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    timeout: 1h
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    timeout: 1h
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  valuesFrom:
    - targetPath: smtp.password
      kind: Secret
      name: lemmy-secret
      valuesKey: smtp_password
    - targetPath: admin.password
      kind: Secret
      name: lemmy-secret
      valuesKey: admin_password
    - targetPath: pictrs.apiKey
      kind: Secret
      name: lemmy-secret
      valuesKey: pictrs_api_key
    - targetPath: postgresql.auth.username
      kind: Secret
      name: lemmy-pguser-lemmy
      valuesKey: user
    # - targetPath: postgresql.auth.password
    #   kind: Secret
    #   name: lemmy-pguser-lemmy
    #   valuesKey: password
    - targetPath: postgresql.host
      kind: Secret
      name: lemmy-pguser-lemmy
      # valuesKey: pgbouncer-host
      valuesKey: host
    - targetPath: config.siteName
      kind: Secret
      name: lemmy-secret
      valuesKey: site_name
  values:
    image:
      repository: dessalines/lemmy
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      #tag: latest

    ## The domain of the Lemmy instance
    serverName: "lemmy.${SECRET_DOMAIN}"

    smtp:
      server: "smtp.sendgrid.net:587"
      username: apikey
      # password:
      from: "lemmy-noreply@${SECRET_DOMAIN}"
      tls: starttls

    admin:
      username: jax-admin
      ## Will be generated on first install if left empty
      # password:
      email: "jax-admin@${SECRET_DOMAIN}"

    config:
      # siteName: Lemmy on Kubernetes
      ## Requires valid certificates, but is also required for federation support
      tls: true
      ## Should pict-rs cache external link previews
      cacheExternalLinkPreviews: true

    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""

    serviceAccount:
      # Specifies whether a service account should be created
      create: true
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""

    backend:
      image:
        _keep: true
        repository: dessalines/lemmy
        pullPolicy: IfNotPresent
        # tag: 0.19.4

      env:
        RUST_BACKTRACE: "full"
        RUST_LOG: "verbose,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"

      envFrom:
        # - secretRef:
        #    name: my-extra-secrets

      replicaCount: 1

      strategy:
        type: RollingUpdate

      livenessProbe:
        httpGet:
          path: /
          port: http
        initialDelaySeconds: 60
        periodSeconds: 3

      readinessProbe:
        httpGet:
          path: /
          port: http
        initialDelaySeconds: 60
        periodSeconds: 3

      startupProbe:
        httpGet:
          path: /
          port: http
        initialDelaySeconds: 120
        periodSeconds: 3

      podAnnotations: {}

      podSecurityContext:
        fsGroup: 1004

      securityContext:
        # capabilities:
        #   drop:
        #   - ALL
        # readOnlyRootFilesystem: true
        # runAsNonRoot: true
        runAsUser: 1004

      service:
        type: ClusterIP
        port: 80

      # resources:
      #   limits:
      #     cpu: 500m
      #     memory: 500Mi
      #   requests:
      #     cpu: 200m
      #     memory: 200Mi

      nodeSelector: {}

      tolerations: []

      affinity: {}

    taskrunner:
      enabled: false

      image:
        _keep: true
        # repository: dessalines/lemmy
        # pullPolicy: IfNotPresent
        # tag:

      env:
        RUST_BACKTRACE: "full"
        RUST_LOG: "verbose,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"

      envFrom:
        # - secretRef:
        #    name: my-extra-secrets

      podAnnotations: {}

      podSecurityContext:
        fsGroup: 1004

      securityContext:
        # capabilities:
        #   drop:
        #   - ALL
        # readOnlyRootFilesystem: true
        # runAsNonRoot: true
        runAsUser: 1004

      resources:
        {}
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
        # requests:
        #   cpu: 100m
        #   memory: 128Mi

      nodeSelector: {}

      tolerations: []

      affinity: {}

    federationsender:
      enabled: false

      image:
        _keep: true
        # repository: dessalines/lemmy
        # pullPolicy: IfNotPresent
        # tag:

      env:
        RUST_BACKTRACE: "full"
        RUST_LOG: "verbose,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
        #RUST_LOG: "warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"

      envFrom:
        # - secretRef:
        #    name: my-extra-secrets

      podAnnotations: {}

      podSecurityContext:
        fsGroup: 1004

      securityContext:
        # capabilities:
        #   drop:
        #   - ALL
        # readOnlyRootFilesystem: true
        # runAsNonRoot: true
        runAsUser: 1004

      resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

      nodeSelector: {}

      tolerations: []

      affinity: {}

    frontend:
      image:
        repository: dessalines/lemmy-ui
        pullPolicy: IfNotPresent
        # tag: 0.19.4

      replicaCount: 1

      strategy:
        type: RollingUpdate

      livenessProbe:
        httpGet:
          path: /robots.txt
          port: http
        initialDelaySeconds: 60
        periodSeconds: 3

      readinessProbe:
        httpGet:
          path: /robots.txt
          port: http
        initialDelaySeconds: 60
        periodSeconds: 3

      startupProbe:
        httpGet:
          path: /robots.txt
          port: http
        initialDelaySeconds: 120
        periodSeconds: 3

      env:
        LEMMY_UI_DEBUG: false
        # RUST_BACKTRACE: "1"
        RUST_LOG: "verbose,lemmy_server=debug,lemmy_api=debug,lemmy_api_common=debug,lemmy_api_crud=debug,lemmy_apub=debug,lemmy_db_schema=debug,lemmy_db_views=debug,lemmy_db_views_actor=debug,lemmy_db_views_moderator=debug,lemmy_routes=debug,lemmy_utils=debug,lemmy_websocket=debug"
        RUST_BACKTRACE: "full"

      envFrom:
        # - secretRef:
        #    name: my-extra-secrets

      podAnnotations: {}

      podSecurityContext:
        fsGroup: 1004

      securityContext:
        # capabilities:
        #   drop:
        #   - ALL
        # readOnlyRootFilesystem: true
        # runAsNonRoot: true
        runAsUser: 1004

      service:
        type: ClusterIP
        port: 80

      # resources:
      #   limits:
      #     cpu: 250m
      #     memory: 250Mi
      #   requests:
      #     cpu: 100m
      #     memory: 100Mi

      nodeSelector: {}

      tolerations: []

      affinity: {}

    pictrs:
      replicaCount: 1

      strategy:
        type: Recreate

      ## Generated on first install if left empty
      # apiKey:

      storage:
        ## Storage method for media, can be filesystem or object_storage
        method: filesystem

        objectStorage:
          ## For self-hosted S3
          # endpoint: https://minio.example.com
          usePathStyle: false

          # bucketName: lemmy-pictrs
          # region:
          # accessKey:
          # secretKey:
          # sessionToken:

          # existingSecret: pictrs-secret
          # existingSecretAccessKey: access-key
          # existingSecretSecretKey: secret-key

      env:
        PICTRS__MEDIA__VIDEO_CODEC: vp9
        PICTRS__MEDIA__GIF__MAX_WIDTH: 256
        PICTRS__MEDIA__GIF__MAX_HEIGHT: 256
        PICTRS__MEDIA__GIF__MAX_AREA: 65536
        PICTRS__MEDIA__GIF__MAX_FRAME_COUNT: 400
        RUST_BACKTRACE: "full"

      envFrom:
        # - secretRef:
        #    name: my-extra-secrets

      image:
        repository: asonix/pictrs
        pullPolicy: IfNotPresent
        # tag: 0.4.0-beta.19

      ## Used by both the sled database and also media itself if using the filesystem storage method
      persistence:
        enabled: true
        accessMode: ReadWriteOnce
        size: 16Gi
        existingClaim: "lemmy-data-pictrs-storage-0"
        storageClass: nfs-client

      livenessProbe:
        httpGet:
          path: /healthz
          port: http

      readinessProbe:
        httpGet:
          path: /healthz
          port: http

      startupProbe:
        httpGet:
          path: /healthz
          port: http

      podAnnotations: {}

      podSecurityContext:
        fsGroup: 1004

      securityContext:
        # capabilities:
        #   drop:
        #   - ALL
        # readOnlyRootFilesystem: true
        # runAsNonRoot: true
        runAsUser: 1004

      service:
        type: ClusterIP
        port: 80

      # resources:
      #   limits:
      #     cpu: 100m
      #     memory: 250Mi
      #   requests:
      #     cpu: 50m
      #     memory: 150Mi

      nodeSelector: {}

      tolerations: []

      affinity: {}

    proxy:
      enabled: true
      replicaCount: 1

      strategy:
        type: RollingUpdate

      image:
        repository: nginx
        pullPolicy: Always
        # tag: 1-alpine

      livenessProbe:
        httpGet:
          path: /
          port: http

      readinessProbe:
        httpGet:
          path: /
          port: http

      podAnnotations: {}

      podSecurityContext:
        {}
        # fsGroup: 2000

      securityContext:
        {}
        # capabilities:
        #   drop:
        #   - ALL
        # readOnlyRootFilesystem: true
        # runAsNonRoot: true
        # runAsUser: 1000

      service:
        type: ClusterIP
        port: 80

      # resources:
      #   limits:
      #     cpu: 100m
      #     memory: 100Mi
      #   requests:
      #     cpu: 50m
      #     memory: 50Mi

      nodeSelector: {}

      tolerations: []

      affinity: {}

    postgresql:
      enabled: false
      sslmode: require
      auth:
        database: lemmy
        existingSecret: "lemmy-pguser-lemmy"
        secretKeys:
          userPasswordKey: "password"

    ingress:
      enabled: true
      className: "nginx"
      annotations:
        # kubernetes.io/ingress.class: nginx
        external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hajimari.io/icon: simple-icons:lemmy
        # kubernetes.io/tls-acme: "true"
      hosts:
        - "lemmy.${SECRET_DOMAIN}"
      tls:
        - secretName: letsencrypt-production
          hosts:
            - "lemmy.${SECRET_DOMAIN}"
