apiVersion: v1
kind: Secret
metadata:
    name: lemmy-secret
    namespace: lemmy
type: Opaque
stringData:
    pictrs_api_key: ENC[AES256_GCM,data:6YgGaN9x6HuE2jRwSxWpNvuEqWHKM1ZT9kT9IzoItUCE/Pgj8afXt1vZl4+6rgAyl6k=,iv:SbvFDbbUTjWyQJ0jFobdGb4fw3EObskn75DAQEXSVtE=,tag:HBv22BnXpRrvWKNqKXk9tw==,type:str]
    smtp_password: ENC[AES256_GCM,data:QJ9T9dfX5PKIzQKP1Jkx2H1hCxCFjEweAV6zDgdYwfFmLyZhxtZ87W4jdYEEoly04fmzDtarIjVNMVIxjc6M9egM9qEX,iv:k0TN50GPQiEu4Ve2EM2XvzJgskaymTKlvLc+0uyXMDo=,tag:Ojycx3t1EB4nIbKedeFrgg==,type:str]
    admin_password: ENC[AES256_GCM,data:iJkDMKOULqquccnuiq6Z0QP9tOFDh9rZTMzJQcfYMjKD02bS2LhMVkEiulkkUwD2K0I=,iv:NxrbU/FyRsoYwmzw/FEy4NOKacJBld0F/UZ5G3n0BSU=,tag:/BFeGZv9SX995kOhRQoukw==,type:str]
    postgresql_password: ENC[AES256_GCM,data:i4ncBLPb6xyZCK8yhyADlKD/G7dIiua272ssiprKcZkAc1+efzfKz120oINP8VZJPhk=,iv:0IiIhGa7ys44NCeNf+khhOODyHxliqBvvpxUal39i9U=,tag:HoAJo+r/lgpcCFMOgfP3WQ==,type:str]
    postgresql_postgres_user_password: ENC[AES256_GCM,data:TaZNUa7bCeeripTz8Qa5HS4wiX84sdZTPxra78XEM2kRo8GF9Cu3/sHG4/7CNl1LXxY=,iv:2BMX/pIAzROhS0gP3TaeT1zzKMp7+WT2A+PJz8OT3II=,tag:Zp7G2OLNyhNNl+RXwIwjyg==,type:str]
    site_name: ENC[AES256_GCM,data:v7CqEKo3ULkxOM4YIZf1,iv:F07ciBvogsWE0U5ZLxg8eCWA40V/dtL+aw0T0f5TYew=,tag:0m4f5uH/121r+UhYOoQtcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ztgva2tc0wsdchee6a8kenhjtcgwzwy8uhlal60zd6wuxuwgvpzslkhnlg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd0ZqbDA2UXBQRnZKdTM4
            clZyNXI5K2ljTU4rYTJ5SWxOZXE0a2loREFFClhsZVpQenJDNHVZUUhMdTk2QkNr
            bE1JdnU4WTRTR1lRakJWeERhcDcxK0kKLS0tIG1GemRJaGNnYmVsem5uNS8vUUh2
            ZkR4dUZtcXFiK0xWYUdadndTZmYrbnMK5dYl4pXdV0kwl2Ejm0KwfG8xT11PPBs9
            fuZOXTO7phNL8b6gpbFUkgG9clp3HjTWeYj4u3TGf+U5WRzNdyI7Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-25T00:07:02Z"
    mac: ENC[AES256_GCM,data:xwvgUH/heRtcxkHOfPPdahrfo9ND5Mm93tIn8JKGdocuSDg8MGWTkeycVJ7pCYy4TXOG3DL0vPMRkwJx0KL7jvL+fYBjOjJHdMJA41jTFa2M6Gv1ZU4KowOqhqxNm2FpCLn9zeNjEShrkPT4SYmE9OpQFIQjWYoTAk82gra4Adw=,iv:dOkNtAVsC/6ETssfmblZO6GqxCWKE0kCyrIPw3UAtDI=,tag:l5pdMuGPfSR4EPK+Jb85XQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
