---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lemmy-lemmy-pictrs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client
