---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: loki-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
  data: # AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: LOKI_AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: LOKI_AWS_SECRET_ACCESS_KEY
