---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./configmap.yaml
  - ./objectbucketclaim.yaml
  - ./helmrelease.yaml
  - ./externalsecret.yaml
labels:
  - pairs:
      app.kubernetes.io/name: loki
      app.kubernetes.io/instance: loki
