---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lm-pgrs
  namespace: lemmy
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      version: 12.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  values:
    global:
      postgresql:
        auth:
          username: lemmy
          database: lemmy
          existingSecret: lm-pgrs-secret
          secretKeys:
            adminPasswordKey: postgresql-password
            userPasswordKey: postgresql-user-password
    image:
      debug: true
    primary:
      persistence:
        enabled: true
        # storageClass: nfs-client
        existingClaim: "data-lemmy-postgresql-0-lemmy-database"
      volumePermissions:
        enabled: true
      containerSecurityContext:
        runAsUser: 1004
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
      serviceMonitor:
        create: true

