---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lm-pgrs
  namespace: lemmy
spec:
  interval: 15m
  chart:
    spec:
      chart: postgres
      version: 12.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  values:
    auth:
      username: lemmy
      existingSecret: lm-pgrs-secret
      secretKeys:
        adminPasswordKey: postgresql-password
        userPasswordKey: postgressql-user-password
    postgresql:
      enabled: true
      image:
        debug: true
      persistence:
        enabled: true
        storageClass: nfs-client
        existingClaim: "data-authentik-postgresql-0-authentik-database"
      volumePermissions:
        enabled: true
      containerSecurityContext:
        runAsUser: 1004
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
      serviceMonitor:
        create: true

