---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lm-pgrs
  namespace: lemmy
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      reconcileStrategy: ChartVersion
      version: 12.5.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
    timeout: 10m
  uninstall:
    keepHistory: false
  values:
    auth:
      username: lemmy
      database: lemmy
      existingSecret: lm-pgrs-secret
      secretKeys:
        adminPasswordKey: postgresql-password
        userPasswordKey: postgresql-user-password
    image:
      debug: true
    primary:
      persistence:
        enabled: true
        # storageClass: nfs-client
        existingClaim: "data-lemmy-postgresql-0-lemmy-database"
      containerSecurityContext:
        enabled: true
        runAsUser: 1004
      podSecurityContext:
        enabled: true
        fsGroup: 1004
      prometheus.io/scrape: "true"
      prometheus.io/path: "/metrics/cluster"
      prometheus.io/port: "9000"
    # volumePermissions:
    #   enabled: true
    #   containerSecurityContext:
    #     runAsUser: 1004
    metrics:
      enabled: true
      prometheusRule:
        enabled: true
      serviceMonitor:
        create: true

