apiVersion: v1
kind: Secret
metadata:
    name: lemmy-postgres-secret
    namespace: flux-system
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:Cq9rvOgFsoo+oSHxujbvmDLzXA+vs3Z/DmFQ6sst5HvzSEm9eg2nS2uE2sX783oGGKA=,iv:mVhroo8l21CyFpyHIjU/zPQV+4+OnKwnntyYzgM08e0=,tag:o8tQcabNXxuTCQFLy0LoAg==,type:str]
    pgadmin-default-email: ENC[AES256_GCM,data:Cxw2UweAF40KytxDzyu4XLgHj3Y6ibLZTQ==,iv:w5HoM23FUpqBJ84k+TlGjt+Y/4ARa51zlPx47RgORjY=,tag:YfDNzJR0S1BZcZjXyX/vJw==,type:str]
    pgadmin-default-password: ENC[AES256_GCM,data:PYiALBriCclH9jwrWjgk6T0Zbnjx01phO8bd2Zdy5C3kxNfglmwULgilmJmEUk+PC/8=,iv:M+ShyMkzjBpt+7OEnvlb6n7RPkUyqr5o9ammUBO3BuI=,tag:bb3f+d/lltDFVuVMXD3Ivw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ztgva2tc0wsdchee6a8kenhjtcgwzwy8uhlal60zd6wuxuwgvpzslkhnlg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCd0ZqbDA2UXBQRnZKdTM4
            clZyNXI5K2ljTU4rYTJ5SWxOZXE0a2loREFFClhsZVpQenJDNHVZUUhMdTk2QkNr
            bE1JdnU4WTRTR1lRakJWeERhcDcxK0kKLS0tIG1GemRJaGNnYmVsem5uNS8vUUh2
            ZkR4dUZtcXFiK0xWYUdadndTZmYrbnMK5dYl4pXdV0kwl2Ejm0KwfG8xT11PPBs9
            fuZOXTO7phNL8b6gpbFUkgG9clp3HjTWeYj4u3TGf+U5WRzNdyI7Dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T21:13:05Z"
    mac: ENC[AES256_GCM,data:wgq+uO3AvTGxRl3zZcJAxiyYoWovY+YcrvCNRxR+jzzArdyHBWoUzeP9/JICVMswh3LqCx0n2itLh7T+8+I531QdsuiDRbKdlGRGvIMikRhI0Yg088NsbVSRkbl5iKnfGrIcQqbmAHnEvRbOzD3kVXLTGwePa56A27Di4Nbuos8=,iv:GMyaigKAgsTfzf1SJT4SEHt8PvEwADUnq7q+8pC2LYQ=,tag:M7vWeP9EE33lpaY/kt8ZbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
