---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-lemmy-database
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 10Gi
  nfs:
    server: 10.0.20.50
    path: >-
      /mnt/Storage/CloudHub-NFS/lemmy-data-lemmy-postgresql-0-lemmy-database
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-lemmy-postgresql-0-lemmy-database
  namespace: lemmy
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-lemmy-database
  storageClassName: nfs-client
  volumeMode: Filesystem
