---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph
  namespace: flux-system
spec:
  path: ./apps/production/rook-ceph/rook-ceph/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-operator
      namespace: rook-ceph
  interval: 30m
  retryInterval: 5m
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-rook-ceph
  path: ./apps/production/rook-ceph/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  retryInterval: 5m
  timeout: 15m
