---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-monitoring-prom-rules
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-kube-prometheus-stack
  path: ./apps/production/monitoring/miscellaneous/prom-rules
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
