apiVersion: v1
kind: Secret
metadata:
    name: github-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:A0+xUlyegetrG1l5HlpIDzK8wB74njDedoaA2An4BNrdcudhUVFXeQ==,iv:eOFswkHDSc9OVir0aaEj7VZn7Qw5o772RZjeiHRrbxs=,tag:EjFr4MsG15kcz730AsZ8ZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ztgva2tc0wsdchee6a8kenhjtcgwzwy8uhlal60zd6wuxuwgvpzslkhnlg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZ25XTVh5Y3J0aTVnaHVT
            QlJvRUtjNjUwUFNzMDJrSWZnd0U3NFAxK0E4CmIzVmZDWVNkcm5ZT3piQkh6S1hX
            RkVyYUdjR3d6UnRjaWMzOWc2ZGNFQzgKLS0tIFJic0d1SXVLNUI1S0hKZUREK2dJ
            aTQ5Z0lKaDFxSHJEeUZKbXZ6Y2ZrNjQKIAG3KVwMyK7F2NfIV4duRlvNkn6CpL08
            lmBZvVvc1HwPWZF2tJEaeX5OqjmonCsYJZZYWdYcidgwTGKRjjXPyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-08T19:30:15Z"
    mac: ENC[AES256_GCM,data:wDzXtsK8dCR4XlmmPXjrtSS5djaxBFQQ7eHtjH4YsNde9ecelxeyhFTPVxxBDqxgXwUtQS99gyDi9BpQoQK4TZV4wSEKWEbkcOEXScKtrs7kQHFalWNHg/mvcDFJguCz16r82Zw7rjRnz1QTs7PvKyHqw/sYKMoqH0dS0G4N1iI=,iv:Eo41JixeCojmy6vDzFG2aLqE8GDDgeVaYFinvcZ62eM=,tag:8xhY/Z9YeXK2xbAzHv6DsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
