---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: reloader
      version: 1.0.72
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: reloader
    reloader:
      reloadStrategy: annotations
      podMonitor:
        enabled: true
