---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vector-aggregator
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: vector-aggregator-secret
    creationPolicy: Owner
  data:
  # GEOIPUPDATE_ACCOUNT_ID, GEOIPUPDATE_LICENSE_KEY
    - secretKey: GEOIPUPDATE_ACCOUNT_ID
      remoteRef:
        key: GEOIPUPDATE_ACCOUNT_ID
    - secretKey: GEOIPUPDATE_LICENSE_KEY
      remoteRef:
        key: GEOIPUPDATE_LICENSE_KEY
