---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: postgres-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: postgres-operator
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    timeout: 30m
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    timeout: 30m
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  values:
    configKubernetes:
      cluster_domain: cluster.local
      cluster_name_label: talos-proxmox-cluster
      enable_readiness_probe: true
      additional_pod_capabilities:
        - "SYS_NICE"
      enable_cross_namespace_secret: true
      configLoadBalancer:
        db_hosted_zone: "db.${SECRET_DOMAIN}"
      # spilo_runasuser: 1004
      # spilo_runasgroup: 1004
      spilo_fsgroup: 1004
      spilo_privileged: true
