---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator-ui
  namespace: postgres-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: postgres-operator-ui
      version: 1.11.0
      sourceRef:
        kind: HelmRepository
        name: postgres-operator-ui
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    timeout: 30m
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    timeout: 30m
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  values:
    envs:
      operatorClusterNameLabel: "talos-proxmox-cluster"
      targetNamespace: "*"
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: |
          10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      ingressClassName: "nginx"
      hosts:
        - host: "postgresui.${SECRET_DOMAIN}"
          paths: ["/"]
      tls:
        - hosts:
            - "postgresui.${SECRET_DOMAIN}"
