---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-operator
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: postgres-operator
      app.kubernetes.io/instance: postgres-operator
      app.kubernetes.io/part-of: postgres-operator
