---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: networking
stringData:
  TUNNEL_ID: "${BOOTSTRAP_CLOUDFLARE_TUNNEL_ID}"
  credentials.json: |
    {
      "AccountTag": "${BOOTSTRAP_CLOUDFLARE_ACCOUNT_TAG}",
      "TunnelSecret": "${BOOTSTRAP_CLOUDFLARE_TUNNEL_SECRET}",
      "TunnelID": "${BOOTSTRAP_CLOUDFLARE_TUNNEL_ID}"
    }
