---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./helmrelease.yaml
labels:
  - pairs:
      app.kubernetes.io/name: external-secrets
      app.kubernetes.io/instance: external-secrets
      app.kubernetes.io/part-of: external-secrets
