---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-fediverse-lemmy-pictrs
  namespace: flux-system
spec:
  dependsOn:
    - name: nfs-client-provisioner
  path: ./apps/fediverse/lemmy/pictrs/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
