---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lemmy-help
  namespace: flux-system
spec:
  interval: 1h
  ref:
    branch: master
  timeout: 1m0s
  url: https://github.com/grouvie/lemmy_help
