---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mastodon
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main
  # Use a chart that fixes upstream issues with duplicate keys
  url: https://github.com/mastodon/chart
  #url: https://github.com/cerebrate/mastodon-chart
