---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: AUTHENTIK_POSTGRESQL_AUTHENTIK_USER_PASSWORD
    - secretKey: AUTHENTIK_POSTGRESQL_POSTGRES_PASSWORD
      remoteRef:
        key: AUTHENTIK_POSTGRESQL_POSTGRES_PASSWORD
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_SENDGRID_API_KEY
      remoteRef:
        key: AUTHENTIK_SENDGRID_API_KEY
