---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2023.6.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  valuesFrom:
    - targetPath: postgresql.postgresqlPassword
      kind: Secret
      name: authentik-secret
      valuesKey: AUTHENTIK_POSTGRESQL__PASSWORD
  values:
    envFrom:
      - secretRef:
          name: authentik-secret
    authentik:
      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.beryju.org, and is fully opt-in
      error_reporting:
        enabled: true
      email:
        from: "Authentik <auth@cloudhub.social>"
        host: "smtp.sendgrid.net"
        port: "587"
        use_tls: true
        username: apikey

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        external-dns.alpha.kubernetes.io/target: "ingress.${SECRET_DOMAIN}"
        hajimari.io/icon: simple-icons:lock
      hosts:
        - host: &host "auth.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host

    postgresql:
      enabled: true
      image:
        debug: true
      persistence:
        enabled: true
        storageClass: nfs-client
        existingClaim: "data-authentik-postgresql-0-authentik-database"
      volumePermissions:
        enabled: true
      containerSecurityContext:
        runAsUser: 1004

    redis:
      enabled: true
      master:
        persistence:
          enabled: true
          storageClass: nfs-client

    prometheus:
      rules:
        create: true
      serviceMonitor:
        create: true
