---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-authentik-database
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 8Gi
  nfs:
    server: 10.0.20.50
    path: >-
      /mnt/Storage/CloudHub-NFS/authentik-data-authentik-postgresql-0-authentik-database
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-client
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-authentik-postgresql-0-authentik-database
  namespace: authentik
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pvc-authentik-database
  storageClassName: nfs-client
  volumeMode: Filesystem
