---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.14.6
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  values:
    # bpf:
    #   masquerade: true
    encryption:
      nodeEncryption: false
    serviceAccounts:
      cilium:
        name: "cilium"
      operator:
        name: "cilium-operator"
    tunnel: vxlan
    cluster:
      name: home-cluster
      id: 1
    securityContext:
      privileged: true
      capabilities:
        ciliumAgent: "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
        cleanCiliumState: "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
    cgroup:
      autoMount:
        enabled: false
      hostRoot: "/sys/fs/cgroup"
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: nginx
          hosts:
            - &host "hubble.${SECRET_DOMAIN}"
          tls:
            - hosts:
                - *host
    ipam:
      mode: kubernetes
    k8sServiceHost: "${KUBE_VIP_ADDR}"
    k8sServicePort: 6443
    kubeProxyReplacement: disabled
    operator:
      replicas: 1
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    rollOutCiliumPods: true
