---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: &namespace kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: external-secrets
      version: 0.8.3
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    serviceMonitor:
      enabled: true
      namespace: *namespace
      interval: 1m
    webhook:
      serviceMonitor:
        enabled: true
        namespace: *namespace
        interval: 1m
    certController:
      serviceMonitor:
        enabled: true
        namespace: *namespace
        interval: 1m
