---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: github-token-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: GITHUB_TOKEN
