---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lemmy-pictrs
  namespace: lemmy
spec:
  interval: 15m
  chart:
    spec:
      chart: pictrs
      version: 0.0.1
      sourceRef:
        kind: GitRepository
        name: lemmy-help
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 10
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 10
  uninstall:
    keepHistory: false
  values:
    namespace: pictrs
    image:
      repository: asonix/pictrs:0.4.0-rc.3
    deployment:
      replicaCount: 1
      terminationGracePeriodSeconds: 10
    service:
      protocol: TCP
      port: 8080
    secret:
      type: Opaque
    pvc:
      storage: 20Gi
      storageClassName: nfs-client
