gh_owner: ENC[AES256_GCM,data:aUoksbDImbULIqw=,iv:NzjzgYygkXZp5k1NQwJk1Sy/8WtfhHqy8MStp5v59ww=,tag:zldTln9GFWNsTH/gA+caWQ==,type:str]
gh_token: ENC[AES256_GCM,data:yCi5ewGZK98zJsMfgcBnAppm2Y6Xuo5pQgrcnnTN5GjJIQJQK4HWbw==,iv:0LBz4jPSg2iWH0QHmr1Ia+KOzfY1SZuvkHeuPkjwhlU=,tag:T3rS5E4zSJRgw/fj893OOw==,type:str]
weave-gitops-password: ENC[AES256_GCM,data:DxCBgNrJ2qYZa4oHU9p8BDObXecp9s1zYUpbQawcukZrLoOMggjpzH4/sQa+CO+4n5KPJgG8n0MUwZpm,iv:JvNoeMgYnKQM347I0gsBfbGNphT4XbdDoxIMOzDXNCQ=,tag:Bvk98RLnvgFADLN6TrVbTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ztgva2tc0wsdchee6a8kenhjtcgwzwy8uhlal60zd6wuxuwgvpzslkhnlg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSEJwOGFVRHNrZUYvQkVL
            TE9WSDZUUkJKSXBVVzkrTWFaaWRTTzd1eEN3CmRyNGtvSlJQRDQyeXI0WjBDRFUx
            Y1VmSnJhdytYbnM1T29UaTR6anpFaTgKLS0tIGVad2sxOVNvWGVHSjFDb1RGZWdJ
            a1BmYWxNUFp3T0JqNFZNTFI1RVVYWXMKmWD0RFgUBs35LMheOGMWR+FboiMGek/6
            0B/viMpu+StjAYmuySMB1qMGAm4i7xj4+KLaASPxw0FQH7BI7vZHVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-22T22:24:41Z"
    mac: ENC[AES256_GCM,data:jV1XEGOvZY2MKFrpZi2taapDn1XUBCs8IUEE94d77A+VXAiJZhXdBqaDhY+0KxkJoZyjrj0q0lZRpjZ/QmjlR/qtU3aKr9A1/Q+hFiXAFNcy2A3USBCyGP8WeKDxU0VEYGQPQ5sDkfvtPEq0slYLco3M05v5z2vqHD6I9MHMMEI=,iv:KFAlAJCRBmrjhztGrC+pzH7y0TG2ocVCqqiDX8mfz1U=,tag:0umFu1WCMv0yBuyezwuymA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
