apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:1D2BJq5B3ks8RAkh4VZW,iv:+N5Bid1X4V/+0R6EPFbVkiI3kc8hHkj0kk5ngoV69os=,tag:hnpFPujyA4h/sfumGT8KMA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:NvPdWMmuJOIIuwdEJjWOPPVrtrK6dA==,iv:ZSOrIXH4AH2padUOhfTikI0DZ+kBymq1A5WcQbYO1sA=,tag:ywilMsmtNj4nF+gua9Y/7w==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:lYOr3gG9EFGcVxYw5s3a9oWT/E6K04SatSwEEITy7gOywwim,iv:yc8BIh9qQIa7TggD9sTbay9DqSaRjMc9x3fFfVQ+L1A=,tag:ASGAzLD5T+7qwwHDtD+iiQ==,type:str]
    SECRET_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:B9odTQHXlmE6p04gp2Tr2PVl+aHITlG+knBhFsWMfgHQk2gArFPk0y3LUDk2zL6xTzxiwvAj/LPt3jA882PZDanuH7STQjWjDHEJ1frFtoE3u2QAH2eLplbMbm/Bk8qU,iv:RLyL1/0XD/CKWQKrlHhGUbUj6sNUo7TdB81M1NnYNyQ=,tag:iKCZBfqfrDc1bTdxTmadbg==,type:str]
    SECRET_CLOUDFLARE_KEY: ENC[AES256_GCM,data:IJBFSUiU7XJEfQlqnId8AVJX6vvdAp32J2+4zzkYRw6FaeMP8Q==,iv:LtyFYzuotH3HJF7rKf1HJjR3IazVdH3cKVxDDbRkG1k=,tag:/sM9U92uDtBA46nwKU27rg==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:7fd32JbEv21M9AJ7GJEF,iv:st6Oq8hF9fAKx5yXyTZ5OjDa0pqH0y1eHnTeMW55n2M=,tag:mUYe4vAlzPUe4YhalNWSyA==,type:str]
    WEAVE_DASHBOARD_PASSWORD: ENC[AES256_GCM,data:t7zoTVkeg0ayAMVz9YfVJB6B8LF+H6oxYOV/n/wFyrsFZy/pWQkRGUctofYPGiF6d96cwx1wuOA2GEdN,iv:4Fq5c9SlcQDH8lhq9ZN4EsCZlEeqp2CWcKTVVb1ktwQ=,tag:Vt7Tb4sbTMZtsCiwVEjqYA==,type:str]
    SECRET_ALERTMANAGER_UPTIMEROBOT_HEARTBEAT_TOKEN: ENC[AES256_GCM,data:FKOymAI2DsWk62FZ+5C+RfVUT2g+L6w0lOSAkW7WrGbdLX5ysPlkLjAEG/p0qGqIo/Tw,iv:pNy9W5S2dgj7rfZLjRpFwTrdaz5cIEeEWZkgGBDqgPg=,tag:cD2y70YCZcuSZPuusoyU0Q==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_TOKEN: ENC[AES256_GCM,data:/1+nIHXWwrfSh/ENsZTISqC6h5CG9Bun6uF6HIJZ,iv:D9F08/niSjyYF1XUtNQCMj/KBf8Si9/fILuDV54WSRs=,tag:Q3KRVPm5b0AR+msEtL7qlA==,type:str]
    SECRET_ALERTMANAGER_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:chxX+2JyocwjttVAJP0jttcEyIZZ5IedKfX6pPP00A==,iv:lGa31x+s/dYk9NMuphSHeExDeUHfaf8bGQc8nO6LEDE=,tag:sNKXDgGikU/OHxpne89zFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ztgva2tc0wsdchee6a8kenhjtcgwzwy8uhlal60zd6wuxuwgvpzslkhnlg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTlBVdXRLakhCd21NVGtx
            VHJBMzVVRzYwZXJSOXRUeTVzMG1mS3RXOER3CmRWek1BM1RHaFYwT0YxVHdnb0N5
            S1R1YlRhQWp5cWpRYjMwV3R0QXJpek0KLS0tIFJSa09qcjRxdFJjMVoreG14UzBp
            RXJLbkp0dlpXakdCcnVtYjV0SCtXNVEKCO9vUBdf4Wnrzp2iuNVP+0vxXcRhxOP0
            CXVMu05bd3rA1h3vyWBZ61aL0EyY/TJVVa4iP9hGhtZAZpNuG4pnaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-07T23:49:17Z"
    mac: ENC[AES256_GCM,data:BpIQhmg7wnBZNbtm2o9CDrGi7n2dSqFwasbcjPUx1kJhUSb6a5HLSuTWmRYM0DYQbaQoCO+4kkXDPB7rlsDS0K/cwLLHAMKhIIemDepJGue6qR0qchKEKCuGD4CRkj/eGFHmCDxE+zdxcxM8SYWqf/N3I8Mh9GH0pAPn1tNm1Ro=,iv:V3NHfKK1Yq0KYsQvwrZGNtsWNMWy2beH4hKPpvTjChQ=,tag:BPBpULW1R59zJIRVoaUXqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
