---
name: "Draft Release"

permissions:
  contents: write
  pull-requests: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@978bb0b30c5ee8cdd332ced253758157150d43f0 # v7.10.0
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
