---
name: "Draft Release"

permissions:
  contents: write
  pull-requests: read

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        with:
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
